---
linters:
    flake8:
    eslint:
        config: './eslint.config'
    csslint:
        ignore: 'scroll-behavior,box-model,ids,order-alphabetical'

files:
    ignore:
        - 'src/generated/*'
        - 'webroot/bower_components/*'