---
linters:
    flake8:
    eslint:
        config: '.eslintrc.js'
    csslint:
        ignore: 'known-properties,box-model,ids,order-alphabetical,important'

files:
    ignore:
        - 'src/generated/*'
        - 'webroot/bower_components/*'